### PR TITLE
Changed the audio cursor width and color to blue

### PR DESCRIPTION
**Pull request by kaustuk**
Feature link: https://github.com/heartexlabs/label-studio/issues/1682

### CODE REVIEW

**Comment by nicholasrq** [comment]
hey! thank you for the contribution

unfortunately we're not ready to merge this PR in its current state as it affects all the Label Studio users who already used to the old style of the cursor

please, make these styles as optional parameters of the Audio tag. this way we won't affect those who's been using Label Studio with old styles

**Comment by kaustuk** [comment]
Hi @nicholasrq , thanks for the reply. Yeah sure will make this optional in audio tag and update this PR

**Comment by nicholasrq** [comment]
great! tag me here when ready and we'll take it to the review

**Comment by kaustuk** [comment]
Hi @nicholasrq, I have modified PR with the change proposed. Please have a look and review it.

**Review by nicholasrq — APPROVED** [review]

**Comment by kaustuk** [comment]
Hi @nicholasrq, @makseq , Thanks for approving this PR :)

Wanted to ask, I can see that the build check is not completed so do I need to do something? Also any idea on when it will get merged?

**Pull request merged**
