### PR TITLE
fix: DEV-3644: Readonly regions should always be selectable

### PR DESCRIPTION
**Pull request by bmartel**

### CODE REVIEW

**Review by Travis1282 — APPROVED** [review]

**Review by hlomzik — CHANGES_REQUESTED** [review]
~~Overall is great, but Taxonomy is editable in readonly~~
Oh nevermind, in readonly Taxonomy is really readonly because dropdown is not rendered at all... And now I understand that we have confusion between `readonly` and `editable`, so we need to discuss it.

**Comment by hlomzik** [comment]
Merged branch of DEV-3391 and DEV-3644: https://github.com/heartexlabs/label-studio-frontend/tree/fb-dev-3391/readonly

**Comment by bmartel** [comment]
@hlomzik 
> ~Overall is great, but Taxonomy is editable in readonly~ Oh nevermind, in readonly Taxonomy is really readonly because dropdown is not rendered at all... And now I understand that we have confusion between `readonly` and `editable`, so we need to discuss it.

This behaviour is what resulted in honouring the readonly nature of the annotation from taxonomy perspective. If this is not correct we should discuss what is expected of the related components. (this likely is an issue with more of the inner components of various configs).

**Comment by bmartel** [comment]
What do we want to do with this branch @hlomzik? These commits are in #928, but if we want to cherry pick the readonly changes it won't be possible without a squash commit of just these changes.

**Pull request merged**
