### PR TITLE
Implements Magic Wand tool for image segmentation

### PR DESCRIPTION
**Pull request by BradNeuberg**
This pull request implements a Magic Wand, making it possible to click in a region of an image a user is doing segmentation labeling on, drag the mouse to dynamically change flood filling tolerance, then release the mouse button to get a new labeled area. It is particularly effective at labeling broad, diffuse, complex edged objects, such as clouds, cloud shadows, snow, etc. in earth observation applications or organic shapes in biomedical applications.

A short video of the tool in action can be seen here: https://www.youtube.com/watch?v=XxjqBx_0-wk

Detailed notes on its implementation can be seen at the top of src/tools/MagicWand.js.

e2e tests still need to be written, these will be added to this PR once done.

### CODE REVIEW

**Comment by BradNeuberg** [comment]
Note that examples/image_magic_wand/annotations/1.json points to a Google Cloud bucket for serving up some example images; before landing this we will want to copy these to your public bucket and change the path. Note that some CORS headers will also have to be set on that bucket in order for the Magic Wand to work from demo images served from it; those changes are documented in the START.md file.

**Comment by BradNeuberg** [comment]
My old code was again label-studio-frontend 1.6.0. I've rebased from `ls-release/1.7.0` and updated the magic wand to work against the latest code. I've opened a new PR to clean up history from this git surgery.

**Comment by farioas** [comment]
Hi @BradNeuberg,
Thank you for your amazing contribution to the project! We're glad to see that you are committed to helping improve and maintain the project.
Please use `master` branch as a target branch for your PR.

**Comment by BradNeuberg** [comment]
I've created a new PR that cleanly branches from master and has my changes, replacing this one: https://github.com/heartexlabs/label-studio-frontend/pull/1119

**Comment by BradNeuberg** [comment]
> Hi @BradNeuberg, Thank you for your amazing contribution to the project! We're glad to see that you are committed to helping improve and maintain the project. Please use `master` branch as a target branch for your PR.

Thanks; turns out I had to make a new PR to do this cleanly, replacing this one: https://github.com/heartexlabs/label-studio-frontend/pull/1119

**Pull request closed without merging**
