### PR TITLE
Fix relations rendering on scroll/resizing

### PR DESCRIPTION
**Pull request by nicholasrq**
We had a problem with relations not being re-rendered when scroll/resize ([#524](https://github.com/heartexlabs/label-studio/issues/524)) happens. This PR introduces the fix for that problem. Relations will also properly react to multiple nested scrolls.

### CODE REVIEW

**Review by evanvin — APPROVED** [review]
Can we get this rebased and merged por favor

**Review by skadecl — APPROVED** [review]

**Comment by skadecl** [comment]
lpgtm, good to rebase and merge

**Comment by skadecl** [comment]
@makseq any chance we can get this merged?

**Comment by makseq** [comment]
@nicholasrq What are you thinking about merging?

**Pull request merged**
